### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by oranenj** [desyops/repository-timeline#1]
I'm looking for tools for lightweight repository snapshots (Katello is the antithesis of lightweight) and this looks like it would at least form a solid base for one, but what license is the code under? I assume it's intended to be free software since it's hosted publicly on Github, but without license information it can't actually be used.

If you don't care about licensing, I recommend the MIT License. It's simple and permissive.

@jengels seems to be the author. Could you comment on this, please?

**Comment by jengels** [comment]
Hi, sorry for the delay. The MIT Licence has now been added. This is just a small tool which we are using at our site to create daily snapshots from our repository mirrors. Hopefully it can also fit your needs. Please feel free to use this software "as is" :)
